src/WebMVC4/Models/GridControlModel.cs
namespace WebMVC4.Models
{
    using System.Linq;
    using Agenda.Model;

    public class GridControlModel
    {
        public GridControlModel(string name)
        {
            this.Name = name;
        }

        public string Name { get; set; }

        public IQueryable<Utenti> ViewModel { get; set; }
    }
}

src/WebMVC4/Controllers/HomeController.cs
namespace WebMVC4.Controllers
{
    using System.Linq;
    using System.Web.Mvc;
    using Agenda.Model;
    using PagedList;

    public class HomeController : Controller
    {
        private const int PageSize = 15;

        // GET: /Home/
        public ActionResult Index(int page = 1)
        {
            using (var context = new AgendaContext())
            {
                var utenti = context.AGE_UTENTI.Where(u => u.Nome.Contains("FABIO"))
                                    .OrderBy(u => u.Cognome)
                                    .ToPagedList(page, PageSize);

                return this.View(utenti);
            }
        }
    }
}

src/WebMVC4/Controllers/TestDXController.cs
namespace WebMVC4.Controllers
{
    using System.Web.Mvc;

    public class TestDXController : Controller
    {
        public ActionResult Index()
        {
            return this.View();
        }
    }
}

src/WebMVC4/Controllers/TestGridViewController.cs
namespace WebMVC4.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using Agenda.Model;
    using WebMVC4.Models;

    public class TestGridViewController : Controller
    {
        private AgendaContext context = new AgendaContext();

        public ActionResult Show()
        {
            var model = new GridControlModel("testGridView") { ViewModel = this.GetUtenti() };

            return this.PartialView(model);
        }

        private IQueryable<Utenti> GetUtenti()
        {
            return this.context.Set<Utenti>().Where(u => u.Nome != null);
        }
    }
}

src/WebMVC4/Controllers/TestUploadController.cs
namespace WebMVC4.Controllers
{
    using System;
    using System.Globalization;
    using System.Web.Mvc;
    using Agenda.Model;
    using Common.Controllers.Upload;

    public class TestUploadController : BaseUploader<string>
    {
        public TestUploadController()
            : base(
                new BlobStorage<AgendaContext, BlobFile>(
                    a => a.Blob,
                    a => a.Id.ToString(CultureInfo.InvariantCulture),
                    OnSave),
                new FileExtensionValidator(
                    new[]
                    {
                        "jpg", 
                        "jpeg", 
                        "png", 
                        "gif", 
                        "bmp", 
                        "pdf", 
                        "doc", 
                        "docx", 
                        "xls", 
                        "xlsx"
                    }))
        {
        }

        private static void OnSave(Controller controller, string identifier, BlobFile file)
        {
            file.NomeFile = identifier;
            file.DataUpload = DateTime.Now;
            file.UserId = "APEX";
        }
    }
}

src/WebMVC4/Views/Home/Index.cshtml
@using PagedList.Mvc

@model PagedList.IPagedList<Agenda.Model.Utenti>

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Kitchen Sink";
}

<style>
    .white-border { border: 1px solid white; }
</style>

<h3>Kitchen Sink</h3>

<div class="divider"></div>
<div class="section">
    <h5>Esempio responsive Grid (provare il resize)</h5>
    <div class="row blue lighten-2  center-align">
        <div class="col s12"><p>s12</p></div>
    </div>
    <div class="row green lighten-2 center-align">
        <div class="col s12 m4 l2 white-border"><p>s12 m4</p></div>
        <div class="col s12 m4 l8 white-border"><p>s12 m4</p></div>
        <div class="col s12 m4 l2 white-border"><p>s12 m4</p></div>
    </div>
    <div class="row orange lighten-2  center-align">
        <div class="col s12 m6 l3 white-border"><p>s12 m6 l3</p></div>
        <div class="col s12 m6 l3 white-border"><p>s12 m6 l3</p></div>
        <div class="col s12 m6 l3 white-border"><p>s12 m6 l3</p></div>
        <div class="col s12 m6 l3 white-border"><p>s12 m6 l3</p></div>
    </div>
</div>

<div class="divider"></div>
<div class="section">
    <h5>Esempio responsive Table (provare il resize) con PagedList</h5>
    <table class="bordered striped highlight responsive-table">
        <thead>
            <tr>
                <th data-field="col1">col1 nome</th>
                <th data-field="col2">col2 cognome</th>
                <th data-field="col3">col3 user</th>
                <th data-field="col4">col4 number</th>
                <th data-field="col5">col5 number</th>
                <th data-field="col6">col6 date</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var utente in Model)
            {
                <tr>
                    <td>@utente.Nome</td>
                    <td>@utente.Cognome</td>
                    <td>@utente.UserId</td>
                    <td>123</td>
                    <td>4,008</td>
                    <td>@DateTime.Now</td>
                </tr>
            }
        </tbody>
    </table>

    <br />
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index", new {page}))
</div>

<div class="divider"></div>
<div class="section">
    <h5>Esempio pulsanti</h5>
    <a class="waves-effect waves-light btn" onclick=" alertify.alert('Alert normale'); ">Test Alertify alert</a>
    <a class="waves-effect waves-light btn" onclick=" alertify.confirm('confirm normale'); "><i class="material-icons left">cloud</i>Test Alertify confirm</a>
    <a class="waves-effect waves-light btn" onclick=" alertify.success('success log normale'); "><i class="material-icons left">thumb_up</i>Test Alertify log success</a>
    <a class="waves-effect waves-light btn" onclick=" alertify.error('success log normale'); "><i class="material-icons left">thumb_down</i>Test Alertify log error</a>
</div>

<div class="divider"></div>
<div class="section">
    <h5>Esempio card</h5>
    <div class="row">
        <div class="col s12 l3">
            <div class="card">
                <div class="card-image">
                    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/La_rocca_malatestiana_di_Cesena.jpg/1280px-La_rocca_malatestiana_di_Cesena.jpg" alt="La rocca maletestiana di Cesena">
                    <span class="card-title">Card Title</span>
                </div>
                <div class="card-content">
                    <p>I am a very simple card. I am good at containing small bits of information. I am convenient because I require little markup to use effectively.</p>
                </div>
                <div class="card-action">
                    <a href="#">This is a link</a>
                    <a href="#">This is a link</a>
                </div>
            </div>
        </div>
        <div class="col s12 l9">
            <div class="valign-wrapper" style="min-height: 500px">
                <h5 class="valign center" style="width: 100%;">la rocca malatestiana di cesena (esempio di allineamento verticale)</h5>
            </div>
        </div>
    </div>
</div>

src/WebMVC4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <title>@ViewBag.Title</title>

        <!--   Common Stylesheets   -->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link href="~/Content/materialize/css/materialize.min.css" rel="stylesheet" />
        <link href="~/content/alertify/alertify.css" rel="stylesheet" />
        <link href="~/Styles/main.css" rel="stylesheet" />
    
        <!-- Common Scripts -->
        <script src="~/Scripts/jquery-2.1.4.min.js"></script>
        <script src="~/Scripts/alertify/alertify.js"></script>
        <script type="text/javascript" src="~/Scripts/select2.min.js"></script>
        <script type="text/javascript" src="~/Scripts/ajax-wrapper.js"></script>
        <script type="text/javascript" src="~/Scripts/materialize/materialize.min.js"></script>

        <script type="text/javascript">
            var BASE_PATH = '@Url.Content("~")';
            $(document).ready(function() {
                //NB: va fatto il reset iniziale per i default
                alertify.reset();

                $(".button-collapse").sideNav();
            });
        </script>

        @RenderSection("Scripts", false)
        
    </head>
<body class="antialiased body-container">
    @Html.DevExpress().GetScripts(
        new Script { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
        new Script { ExtensionSuite = ExtensionSuite.HtmlEditor },
        new Script { ExtensionSuite = ExtensionSuite.GridView },
        new Script { ExtensionSuite = ExtensionSuite.PivotGrid },
        new Script { ExtensionSuite = ExtensionSuite.Editors },
        new Script { ExtensionSuite = ExtensionSuite.Chart },
        new Script { ExtensionSuite = ExtensionSuite.Report },
        new Script { ExtensionSuite = ExtensionSuite.Scheduler },
        new Script { ExtensionSuite = ExtensionSuite.TreeList }
    )

    @Html.DevExpress().GetStyleSheets(
        new StyleSheet { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
        new StyleSheet { ExtensionSuite = ExtensionSuite.Editors },
        new StyleSheet { ExtensionSuite = ExtensionSuite.HtmlEditor },
        new StyleSheet { ExtensionSuite = ExtensionSuite.GridView },
        new StyleSheet { ExtensionSuite = ExtensionSuite.PivotGrid },
        new StyleSheet { ExtensionSuite = ExtensionSuite.Chart },
        new StyleSheet { ExtensionSuite = ExtensionSuite.Report },
        new StyleSheet { ExtensionSuite = ExtensionSuite.Scheduler },
        new StyleSheet { ExtensionSuite = ExtensionSuite.TreeList }
    )

    @Html.Partial("_TopBar")

    @RenderBody()

</body>

</html>

src/WebMVC4/Views/Shared/_TopBar.cshtml
<nav>
    <div class="nav-wrapper">
        <a href="#" class="brand-logo">Web MVC4</a>
        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
            <li>@Html.ActionLink("Home","Index","Home")</li>
            <li>@Html.ActionLink("Test DevExpress", "Index", "TestDX")</li>
        </ul>
        <ul class="side-nav" id="mobile-demo">
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li>@Html.ActionLink("Test DevExpress", "Index", "TestDX")</li>
        </ul>
    </div>
</nav>

src/WebMVC4/Views/TestDX/Index.cshtml
@{
    ViewBag.Title = "Test DevExpress";
}

<h2>Test DevExpress</h2>

<h3>Navbar</h3>

@Html.DevExpress().NavBar(settings =>
    {
        settings.Name = "testNavBar";
        settings.Groups.Add("Group1").Items.Add("Item1-1");
        settings.Groups.Add("Group2").Items.Add("Item2-1");
        settings.Groups.FindByText("Group2").Expanded = false;
    }).GetHtml()

<div style="margin: 100px;">
    <h3>Grid view</h3>

    @Html.Action("Show", "TestGridView")
</div>

<div style="margin: 100px; max-width: 500px;">
    <h3>Uploader</h3>

    @Html.Action(
        "FileUploader",
        "TestUpload",
        new
        {
            controlName = "dxFileUploader",
            identifierName = "file"
        })
</div>

src/WebMVC4/Views/TestGridView/Show.cshtml
@model WebMVC4.Models.GridControlModel

@Html.DevExpress().GridView(settings =>
    {
        settings.Name = "UtentiGrid";
        settings.KeyFieldName = "UserId";
        settings.CallbackRouteValues = new { Controller = "TestGridView", Action = "Show" };

        settings.Columns.Add("UserId");
        settings.Columns.Add("Nome");
        settings.Columns.Add("Cognome");


        settings.Settings.ShowFilterRow = true;
        settings.Settings.ShowGroupPanel = true;
        settings.Settings.ShowFooter = true;
        settings.EnableRowsCache = false;

    }).BindToLINQ(string.Empty, string.Empty, (s, e) =>
    {
        e.QueryableSource = Model.ViewModel;
        e.KeyExpression = "UserId";
    }).GetHtml()